sudo: required
language: python
python:
- '3.5'
env:
  matrix:
  - REDIS_LOCATION=localhost:6379
services:
- redis
- docker
install:
- pip install -r requirements.txt
script:
- python manage.py test --settings=codemetric.settings
- CODECLIMATE_REPO_TOKEN=fa6f5e950baef17fdf7c4affc694aed03dc3ae0a886dc5ecec82de6079d710b0
  codeclimate-test-reporter
- test $TRAVIS_BRANCH == "master" && docker login -u=discoveryregistry -p=/Qgk0+YPweZLKFiO+olW1/LNwCpl38Az discoveryregistry-on.azurecr.io & docker build -t discoveryregistry-on.azurecr.io/codemetrics:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER . && docker push discoveryregistry-on.azurecr.io/codemetrics:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER
