language: python
python:
  - "3.5"
env:
  - MEMCACHE_LOCATION=localhost:11211 REDIS_LOCATION=localhost:6379
services:
  - memcached
# command to install dependencies
install:
  - "pip install -r requirements.txt"
script:
  - python manage.py test --settings=codemetric.settings
addons:
    code_climate:
        repo_token: fa6f5e950baef17fdf7c4affc694aed03dc3ae0a886dc5ecec82de6079d710b0
after_sucess:
  - CODECLIMATE_REPO_TOKEN=fa6f5e950baef17fdf7c4affc694aed03dc3ae0a886dc5ecec82de6079d710b0 codeclimate-test-reporter
deploy:
  provider: azure_web_apps
  on:
    branch: master
  username: AZURE_WA_USERNAME
  password: AZURE_WA_PASSWORD
  site: AZURE_WA_SITE