sudo: required
language: python
python:
- '3.5'
env:
  matrix:
  - REDIS_LOCATION=localhost:6379
services:
- redis
- docker
install:
- pip install -r requirements.txt
script:
- python manage.py test --settings=codemetric.settings
after_success:
- codeclimate-test-reporter --token $CODECLIMATE_TOKEN
- if [ $TRAVIS_BRANCH == "master" ]; then
  docker login -u=$DOCKER_USER -p=$DOCKER_PWD $DOCKER_URL ;
  docker build -t $DOCKER_URL/codemetrics:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER .;
  docker push discoveryregistry-on.azurecr.io/codemetrics:$APP_MAJOR_VERSION.$APP_MINOR_VERSION.$TRAVIS_BUILD_NUMBER ;
  fi
